name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.6, 2.5, 2.4]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@master
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - run: gem install bundler
    - run: bundle install --jobs 4 --retry 3
    - run: bundle exec rake spec
